remote:
 reportServerIP: 39.99.137.69:8075
# mesServerIP: localhost:8090
 mesServerIP: localhost:8080

server:
 port: 80
 servlet:
  session:
   timeout: 3600s

spring:
 http:
  encoding:
   charset: UTF-8
   enabled: true
   force: true
 
 thymeleaf:
#  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  #非严格的HTML5标签格式，需要依赖nekohtml和unbescape两个jar包
  mode: LEGACYHTML5
  #关闭缓存，开发时关闭，上线后打开
  cache: true
