mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.ynan.entity
    type-handlers-package: com.ynan.typeHandler
    # executor-type: REUSE
    configuration:
       # logImpl: STDOUT_LOGGING
        logImpl: com.ynan.log.MyCustomLog
        cache-enabled: false


jdbc:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.24.106:3306/test?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456